// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Unposed",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Unposed",
            targets: ["Unposed"],
            bundleIdentifier: "com.unposed.app",
            teamIdentifier: "54U942ZGP8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            capabilities: [
                .camera(purposeString: "Unposed needs camera access to capture your candid moments."),
                .photoLibraryAdd(purposeString: "Unposed needs access to save your photo strips to your Photos library.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "Unposed",
            path: "Sources/Unposed"
        )
    ]
)